subscribers5 veritabanı gcp ye taşında ve router ve model daki fonksiyonlar güncellendi ayrıca ejs dosyası güncellendi.

diff --git a/.github/workflows/deployToGcp.yml b/.github/workflows/deployToGcp.yml
--- a/.github/workflows/deployToGcp.yml
+++ b/.github/workflows/deployToGcp.yml
@@ -32,6 +32,12 @@ jobs:
 
     - name: Set GOOGLE_APPLICATION_CREDENTIALS environment variable
       run: |
-        echo "${{ secrets.GCP_APP_KEY_64 }}" | base64 --decode > $HOME/gcp_key.json
+        echo "${{ secrets.GCPCLOUDFIRESTOREBASE64JSONKEY }}" | base64 --decode > $HOME/gcp_key.json
         echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp_key.json" >> $GITHUB_ENV
-        gcloud app deploy --quiet
+
+    - name: Debug Base64 Decoding
+      run: |
+        cat $HOME/gcp_key.json || echo "File creation failed or file is empty"
+
+    - name: Deploy to Google App Engine
+      run: gcloud app deploy --quiet
